services:
  db:
    image: postgres:15
    networks:
      - network_fpi
    environment:
      POSTGRES_USER: discorre1
      POSTGRES_PASSWORD: 0412
      POSTGRES_DB: bank
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U discorre2 -d bank"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build: ./fpibank-system
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://discorre2:0412@db:5432/bank
      SECRET_KEY: eb4ae8f8c330008117d25836b4b27ecd4fefdac5f1492d8101226350c667ff9b
      ALGORITHM: HS256
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    networks:
      - network_fpi
    
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - network_fpi
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  frontend:
    build:
      context: ./fpibank-client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./fpibank-client/certs/discorre.ru:/etc/letsencrypt/live/discorre.ru

    networks:
      - network_fpi
  
  # mitmproxy:
  #   build:
  #     context: ./sniffer
  #   ports:
  #     - "8080:8080"   
  #     - "8081:8081"
  #     - "8082:8082"  
  #   volumes:
  #     - ./certs:/certs 
  #     - ./attack_logs.json:/app/attack_logs.json
  #     - ./templates:/app/templates       
  #     - ./main.py:/app/main.py    
  #   depends_on:
  #     - backend
  #   networks:
  #     - network_fpi
  #   environment:
  #     - LOG_FILE=/app/attack_logs.json


volumes:
  db_data:
  redis_data:
  letsencrypt:
  letsencrypt_data:
  letsencrypt_logs:

networks:
  network_fpi:
    driver: bridge